import 'package:sport_finding/feature/model/app_user.dart';
import 'package:sport_finding/feature/model/discovery_match.dart';

class DiscoveryMatchData {
  /// Seed ids treated as hosted by [AppUser.current] (demo data).
  static const Set<String> _idsHostedByCurrentUser = {
    'h0',
    '1',
    '2',
    '11',
    '21',
    '31',
    'p2',
  };

  static List<DiscoveryMatch> get allMatches => _seedMatches
      .map(
        (m) => m.copyWith(
          hostUserId: _idsHostedByCurrentUser.contains(m.id)
              ? AppUser.current.id
              : 'host_external_${m.id}',
        ),
      )
      .toList();

  static final List<DiscoveryMatch> _seedMatches = [
    // First in lists: you host, upcoming — shows “You’re hosting” in UI.
    DiscoveryMatch(
      id: 'h0',
      title: 'Your pickup game',
      distanceKm: 0.6,
      sportType: 'Football',
      location: 'Riverside Grounds',
      date: '30/03/2026',
      time: '7:00 PM',
      participantsJoined: 4,
      participantsTotal: 10,
      players: ['Ali', 'Usman'],
      hostDisplayName: 'Shehzad Khan',
      skillLevel: 'Intermediate',
      matchDescription: 'Casual evening kickabout. All levels welcome.',
      hostBio: 'Local organiser — join any time.',
      hostMatchesPlayed: 24,
    ),
    // Football Matches
    DiscoveryMatch(
      id: '1',
      title: 'City Football League',
      distanceKm: 1.5,
      sportType: 'Football',
      location: 'Central Park Stadium',
      date: '05/04/2026',
      time: '4:00 PM',
      participantsJoined: 8,
      participantsTotal: 11,
      players: ['Ali', 'Usman', 'Ahmad'],
      hostDisplayName: 'Shehzad Khan',
      skillLevel: 'Intermediate',
      matchDescription:
          'Friendly league night at Central Park Stadium. Intermediate level, '
          'about two hours. Bring your own ball if you can.',
      hostBio: 'Organizes weekly football in the city. All about fair play.',
      playerSkills: ['Advanced', 'Intermediate', 'Advanced'],
      hostMatchesPlayed: 42,
    ),
    DiscoveryMatch(
      id: '2',
      title: 'Sunday Football Fun',
      distanceKm: 2.3,
      sportType: 'Football',
      location: 'Greenfield Arena',
      date: '09/04/2026',
      time: '5:30 PM',
      participantsJoined: 6,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '3',
      title: 'Evening Kickoff',
      distanceKm: 3.0,
      sportType: 'Football',
      location: 'Riverside Grounds',
      date: '28/03/2026',
      time: '6:00 PM',
      participantsJoined: 9,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad", "Shehzad Khan"],
    ),
    DiscoveryMatch(
      id: '4',
      title: 'Neighborhood Football',
      distanceKm: 0.8,
      sportType: 'Football',
      location: 'Maple Street Field',
      date: '29/03/2026',
      time: '3:30 PM',
      participantsJoined: 5,
      participantsTotal: 8,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '5',
      title: 'Friendly Match',
      distanceKm: 2.7,
      sportType: 'Football',
      location: 'Hilltop Sports Complex',
      date: '30/03/2026',
      time: '4:30 PM',
      participantsJoined: 7,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '6',
      title: 'City Champs',
      distanceKm: 1.2,
      sportType: 'Football',
      location: 'Downtown Arena',
      date: '31/03/2026',
      time: '5:00 PM',
      participantsJoined: 10,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '7',
      title: 'Morning Football',
      distanceKm: 1.9,
      sportType: 'Football',
      location: 'Sunrise Field',
      date: '01/04/2026',
      time: '8:30 AM',
      participantsJoined: 4,
      participantsTotal: 8,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '8',
      title: 'Weekend Football',
      distanceKm: 3.2,
      sportType: 'Football',
      location: 'Lakeside Stadium',
      date: '02/04/2026',
      time: '10:00 AM',
      participantsJoined: 11,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '9',
      title: 'Friendly Cup',
      distanceKm: 2.0,
      sportType: 'Football',
      location: 'Oakwood Field',
      date: '03/04/2026',
      time: '6:30 PM',
      participantsJoined: 9,
      participantsTotal: 11,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '10',
      title: 'City League Finals',
      distanceKm: 1.6,
      sportType: 'Football',
      location: 'National Sports Complex',
      date: '04/04/2026',
      time: '7:00 PM',
      participantsJoined: 12,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),

    // Tennis Matches
    DiscoveryMatch(
      id: '11',
      title: 'City Tennis Open',
      distanceKm: 1.2,
      sportType: 'Tennis',
      location: 'Central Tennis Court',
      date: '11/04/2026',
      time: '4:00 PM',
      participantsJoined: 2,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '12',
      title: 'Evening Tennis Rally',
      distanceKm: 2.0,
      sportType: 'Tennis',
      location: 'Greenwood Tennis Club',
      date: '27/03/2026',
      time: '5:30 PM',
      participantsJoined: 3,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '13',
      title: 'Weekend Smash',
      distanceKm: 3.5,
      sportType: 'Tennis',
      location: 'Riverside Courts',
      date: '28/03/2026',
      time: '3:00 PM',
      participantsJoined: 1,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '14',
      title: 'Friendly Tennis Match',
      distanceKm: 0.9,
      sportType: 'Tennis',
      location: 'Maple Street Tennis Arena',
      date: '29/03/2026',
      time: '6:00 PM',
      participantsJoined: 2,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '15',
      title: 'Tennis Club Finals',
      distanceKm: 2.2,
      sportType: 'Tennis',
      location: 'Hilltop Tennis Complex',
      date: '30/03/2026',
      time: '4:30 PM',
      participantsJoined: 4,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '16',
      title: 'Morning Tennis Practice',
      distanceKm: 1.5,
      sportType: 'Tennis',
      location: 'Downtown Tennis Courts',
      date: '31/03/2026',
      time: '8:00 AM',
      participantsJoined: 1,
      participantsTotal: 2,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '17',
      title: 'Neighborhood Tennis Rally',
      distanceKm: 1.8,
      sportType: 'Tennis',
      location: 'Sunrise Tennis Field',
      date: '01/04/2026',
      time: '9:30 AM',
      participantsJoined: 2,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '18',
      title: 'City Tennis Championship',
      distanceKm: 2.5,
      sportType: 'Tennis',
      location: 'Lakeside Tennis Courts',
      date: '02/04/2026',
      time: '5:00 PM',
      participantsJoined: 3,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '19',
      title: 'Friendly Doubles Match',
      distanceKm: 2.1,
      sportType: 'Tennis',
      location: 'Oakwood Tennis Club',
      date: '03/04/2026',
      time: '6:30 PM',
      participantsJoined: 4,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '20',
      title: 'City Tennis League',
      distanceKm: 1.6,
      sportType: 'Tennis',
      location: 'National Tennis Arena',
      date: '04/04/2026',
      time: '7:00 PM',
      participantsJoined: 3,
      participantsTotal: 4,
      players: ["Ali", "Usman", "Ahmad"],
    ),

    // Volleyball Matches 21-30
    DiscoveryMatch(
      id: '21',
      title: 'City Volleyball League',
      distanceKm: 2.0,
      sportType: 'Volleyball',
      location: 'City Sports Center',
      date: '14/04/2026',
      time: '5:30 PM',
      participantsJoined: 6,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '22',
      title: 'Beach Volleyball Fun',
      distanceKm: 3.2,
      sportType: 'Volleyball',
      location: 'Sunny Beach Courts',
      date: '27/03/2026',
      time: '4:00 PM',
      participantsJoined: 8,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '23',
      title: 'Evening Spike Match',
      distanceKm: 1.8,
      sportType: 'Volleyball',
      location: 'Riverside Volleyball Arena',
      date: '28/03/2026',
      time: '6:00 PM',
      participantsJoined: 5,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '24',
      title: 'Neighborhood Volleyball',
      distanceKm: 0.9,
      sportType: 'Volleyball',
      location: 'Maple Street Court',
      date: '29/03/2026',
      time: '3:30 PM',
      participantsJoined: 4,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '25',
      title: 'Friendly Match',
      distanceKm: 2.5,
      sportType: 'Volleyball',
      location: 'Hilltop Sports Complex',
      date: '30/03/2026',
      time: '5:00 PM',
      participantsJoined: 7,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '26',
      title: 'City Champs Volleyball',
      distanceKm: 1.3,
      sportType: 'Volleyball',
      location: 'Downtown Arena',
      date: '31/03/2026',
      time: '6:30 PM',
      participantsJoined: 10,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '27',
      title: 'Morning Volleyball Practice',
      distanceKm: 2.1,
      sportType: 'Volleyball',
      location: 'Sunrise Sports Field',
      date: '01/04/2026',
      time: '8:30 AM',
      participantsJoined: 3,
      participantsTotal: 8,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '28',
      title: 'Weekend Volleyball Rally',
      distanceKm: 3.0,
      sportType: 'Volleyball',
      location: 'Lakeside Stadium',
      date: '02/04/2026',
      time: '10:00 AM',
      participantsJoined: 9,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '29',
      title: 'Friendly Cup Volleyball',
      distanceKm: 2.0,
      sportType: 'Volleyball',
      location: 'Oakwood Court',
      date: '03/04/2026',
      time: '6:30 PM',
      participantsJoined: 8,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '30',
      title: 'City League Finals Volleyball',
      distanceKm: 1.5,
      sportType: 'Volleyball',
      location: 'National Sports Complex',
      date: '04/04/2026',
      time: '7:00 PM',
      participantsJoined: 12,
      participantsTotal: 12,
      players: ["Ali", "Usman", "Ahmad"],
    ), // Basketball Matches 31-40
    DiscoveryMatch(
      id: '31',
      title: 'City Basketball League',
      distanceKm: 1.5,
      sportType: 'Basketball',
      location: 'Downtown Basketball Court',
      date: '18/04/2026',
      time: '6:00 PM',
      participantsJoined: 8,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '32',
      title: 'Evening Hoops',
      distanceKm: 2.3,
      sportType: 'Basketball',
      location: 'Greenfield Arena',
      date: '27/03/2026',
      time: '7:30 PM',
      participantsJoined: 6,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '33',
      title: 'Weekend Basketball Clash',
      distanceKm: 3.1,
      sportType: 'Basketball',
      location: 'Riverside Court',
      date: '28/03/2026',
      time: '5:00 PM',
      participantsJoined: 9,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '34',
      title: 'Friendly Basketball Match',
      distanceKm: 1.0,
      sportType: 'Basketball',
      location: 'Maple Street Court',
      date: '29/03/2026',
      time: '4:30 PM',
      participantsJoined: 5,
      participantsTotal: 8,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '35',
      title: 'Street Basketball',
      distanceKm: 2.6,
      sportType: 'Basketball',
      location: 'Hilltop Sports Complex',
      date: '30/03/2026',
      time: '6:30 PM',
      participantsJoined: 7,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '36',
      title: 'City Champs Basketball',
      distanceKm: 1.4,
      sportType: 'Basketball',
      location: 'National Sports Arena',
      date: '31/03/2026',
      time: '7:00 PM',
      participantsJoined: 10,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '37',
      title: 'Morning Basketball Practice',
      distanceKm: 2.0,
      sportType: 'Basketball',
      location: 'Sunrise Court',
      date: '01/04/2026',
      time: '8:00 AM',
      participantsJoined: 4,
      participantsTotal: 8,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '38',
      title: 'Neighborhood Hoops',
      distanceKm: 1.8,
      sportType: 'Basketball',
      location: 'Oakwood Court',
      date: '02/04/2026',
      time: '5:30 PM',
      participantsJoined: 6,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '39',
      title: 'Friendly Cup Basketball',
      distanceKm: 2.2,
      sportType: 'Basketball',
      location: 'Lakeside Arena',
      date: '03/04/2026',
      time: '6:00 PM',
      participantsJoined: 9,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    DiscoveryMatch(
      id: '40',
      title: 'Basketball League Finals',
      distanceKm: 1.6,
      sportType: 'Basketball',
      location: 'City Sports Complex',
      date: '04/04/2026',
      time: '8:00 PM',
      participantsJoined: 10,
      participantsTotal: 10,
      players: ["Ali", "Usman", "Ahmad"],
    ),
    // Past dates — hidden from "All Upcoming"; "p2" still appears under My Matches (you host).
    DiscoveryMatch(
      id: 'p1',
      title: 'Early March Friendly',
      distanceKm: 2.0,
      sportType: 'Football',
      location: 'Old Town Pitch',
      date: '08/03/2026',
      time: '11:00 AM',
      participantsJoined: 6,
      participantsTotal: 10,
      players: ['Ali', 'Usman'],
    ),
    DiscoveryMatch(
      id: 'p2',
      title: 'Your Tuesday League (past)',
      distanceKm: 1.0,
      sportType: 'Football',
      location: 'Main Ground',
      date: '11/03/2026',
      time: '2:00 PM',
      participantsJoined: 10,
      participantsTotal: 10,
      players: ['Ali', 'Usman', 'Ahmad'],
    ),
  ];
}
